/*
* @file Constants.h
*
* @brief Constants
*
*/
#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_NUM_OF_ROOMS 5
#define NEW_SERVER_RETRIES 3

#define MAX_NUM_OF_SOIL_SENSORS		10	// Maximum 255 (uint8)
#define MAX_NUM_OF_ENV_SENSORS		10
#define MAX_NUM_OF_CONTROLLERS_HP	11
#define MAX_NUM_OF_CONTROLLERS_LP	10
#define MAX_NUM_OF_HYDRO			10
#define MAX_NUM_OF_THINGS			(MAX_NUM_OF_SOIL_SENSORS + MAX_NUM_OF_ENV_SENSORS + MAX_NUM_OF_CONTROLLERS_HP + MAX_NUM_OF_CONTROLLERS_LP + MAX_NUM_OF_HYDRO)

//										LSB | B0  | B1 |  B2 |  B3 |  B4 |  MSB 
#define NRF_ADDRESS_GATEWAY_1_SOIL_SENSORS	{0xA8, 0xC4, 0xD2, 0xF0, 0xA3}
#define NRF_ADDRESS_GATEWAY_2_ENV_SENSORS	{0xD5, 0xC4, 0xD2, 0xF0, 0xA3}
#define NRF_ADDRESS_GATEWAY_3_CONTROLLERS	{0xA5, 0xC4, 0xD2, 0xF0, 0xA3}
#define NRF_ADDRESS_GATEWAY_4_HYDROS		{0xB4, 0xC4, 0xD2, 0xF0, 0xA3}
#define NRF_ADDRESS_GATEWAY_5_EXT			{0xC8, 0xC4, 0xD2, 0xF0, 0xA3}
	
#define NRF_ADDRESS_GATEWAY_1_LSB_SOIL_SENSORS	0xA8
#define NRF_ADDRESS_GATEWAY_2_LSB_ENV_SENSORS	0xD5
#define NRF_ADDRESS_GATEWAY_3_LSB_CONTROLLERS	0xA5
#define NRF_ADDRESS_GATEWAY_4_LSB_HYDROS		0xB4
#define NRF_ADDRESS_GATEWAY_5_LSB_EXT			0xC8

#define TESTING_NRF_ADDR_SIMULATOR		  {0xA5, 0xB3, 0xD3, 0xF4, 0xE5}
#define TESTING_NRF_ADDR_THING_SENSOR_1   {0xF1, 0xE6, 0xC8, 0xA9, 0xD1}
#define TESTING_NRF_ADDR_THING_CONTR_HP_1 {0xE3, 0xA2, 0xB3, 0xB8, 0xF4}
#define TESTING_UUID_SENSOR_1 10001
#define TESTING_UUID_CONTROLLER_HP_1 10010
#define TESTING_TIME_SET 1674837068
#define NRF_CHECK_STATUS_INTERVAL_SEC 5
#define THING_STATUS_TIMEOUT_SEC 10
#define NRF_DB_STRORE_INTERVAL 60
#define THING_UUID_MIN_VALUE		10
#define THING_UUID_MAX_VALUE		65535
#define MASK_CTRL_DEVICE_TYPE_1		0x0F
#define MASK_CTRL_DEVICE_TYPE_2		0xF0
#define CONTROLLER_HP_CONNECTION_TICKS 80 // tick x timer interrupt = 80 x 50ms = 4000ms
#define CONTROLLER_HP_MEASUREMENTS_TICKS 1200 // tick x timer interrupt = 80 x 50ms = 60000ms
#define CONTROLLER_HP_CONSUMPTION_SENSITIVITY 185 // 185 mV for 30A ACS712
#define CONTROLLER_HP_CONSUMPTION_SAMPLES	100

#define TEMPERATURE_NUM_OF_DIGITS	5
#define TEMPERATURE_NUM_OF_DECIMAL	2

#define TIMER_NUM_OF_DIGITS			5
#define TIMER_NUM_OF_DECIMAL		2
			
#define BATTERY_ECO_VALUE_DEFAULT	1
#define BATTERY_ECO_VALUE_MIN		1
#define BATTERY_ECO_VALUE_MAX		255
#define BATTERY_ECO_OFFSET_SEC		30
#define BATTERY_ECO_VALUE_UNDEFINED	BATTERY_ECO_VALUE_MAX + 1

#define BATTERY_VD_R1 1000000.0
#define BATTERY_VD_R2 470000.0
#define BATTERY_VD_VREF 1100.0
#define BATTERY_VD_OFFSET .0
#define BATTERY_MV_MAX 3440	// Note: This value is the equivalent voltage of 1.1V reference. Is calculated based on R2,R3 resistors.
#define BLINK_DURATION_SEC			10
#define BUTTON_LONG_PRESS_DURATION_SEC	3
#define SOIL_ADC_ERROR_OFFSET		5
#define BUTTON_LONG_PRESS_TICKS	300	// tick x timer interrupt = long press duration (300 ticks x 10ms timer = 3 seconds)
#define NUM_OF_EVENTS_TO_SEND 32
#define MAX_NUM_OF_CHARS_IPV4 15+1
#define MAX_NUM_OF_CHARS_CLIENT_ID 10
#define MAX_NUM_OF_CHARS_VHOST 10
#define MAX_NUM_OF_CHARS_USER 10
#define MAX_NUM_OF_CHARS_PASS 10

#endif

/*** end of file ***/

