/*
* @file RF_packets.h
*
* @brief The offsets for the RF packets
*
*/

#ifndef RF_PACKETS_H
#define RF_PACKETS_H

// Global
#define MASK_TYPE					0x07
#define MASK_HW_CHANGE				0x08
#define MASK_SW_CHANGE				0x10
#define MASK_BLINK					0x20

#define BIT_OFFSET_TYPE				0
#define BIT_OFFSET_HW_CHANGE		3
#define BIT_OFFSET_SW_CHANGE		4
#define BIT_OFFSET_BLINK			5

#define OFFSET_UUID					0
#define OFFSET_FLAGS				2
#define OFFSET_PKT_ID				3
#define OFFSET_ADDRESS				4

// Soil Sensor
#define OFFSET_SOIL_SENSOR_ECO		9
#define OFFSET_SOIL_SENSOR_BATTERY	10
#define OFFSET_SOIL_SENSOR_STATE	12

#define BIT_OFFSET_STATE_CH_1		0
#define BIT_OFFSET_STATE_CH_2		1
#define BIT_OFFSET_STATE_CH_3		2
#define BIT_OFFSET_STATE_CH_4		3

#define OFFSET_SOIL_SENSOR_SOIL_1	13
#define OFFSET_SOIL_SENSOR_SOIL_2	14
#define OFFSET_SOIL_SENSOR_SOIL_3	15
#define OFFSET_SOIL_SENSOR_SOIL_4	16

#define OFFSET_SOIL_SENSOR_SOIL_1_TH_LOW	17
#define OFFSET_SOIL_SENSOR_SOIL_1_TH_HIGH	18
#define OFFSET_SOIL_SENSOR_SOIL_2_TH_LOW	19
#define OFFSET_SOIL_SENSOR_SOIL_2_TH_HIGH	20
#define OFFSET_SOIL_SENSOR_SOIL_3_TH_LOW	21
#define OFFSET_SOIL_SENSOR_SOIL_3_TH_HIGH	22
#define OFFSET_SOIL_SENSOR_SOIL_4_TH_LOW	23
#define OFFSET_SOIL_SENSOR_SOIL_4_TH_HIGH	24

// Environment Sensor
#define OFFSET_ENV_SENSOR_ECO		9
#define OFFSET_ENV_SENSOR_BATTERY	10
#define OFFSET_ENV_SENSOR_TEMP		12
#define OFFSET_ENV_SENSOR_HUM		14
#define OFFSET_ENV_SENSOR_CO2		15
#define OFFSET_ENV_SENSOR_SPECTRUM	17

// Controller HP and LP
#define MASK_SCHEDULER				0x07
#define MASK_STATE					0x08
#define MASK_AUTO					0x10

#define BIT_OFFSET_SCHEDULER		0
#define BIT_OFFSET_STATE			3
#define BIT_OFFSET_AUTO				4

#define OFFSET_CTRL_CLOCK			9

#define SUB_CONTROLLER_SIZE			9
#define OFFSET_CTRL_CONTROL			13
#define OFFSET_CTRL_DAYS			14
#define OFFSET_CTRL_TIMER_ON		15
#define OFFSET_CTRL_TIMER_OFF		17
#define OFFSET_CTRL_CONSUMPTION		19
#define OFFSET_CTRL_CONSUMPTION_TS	21

#endif

/*** end of file ***/